### ISSUE TITLE
Download Data Issue

### ISSUE THREAD

**Issue by MitraDarja** [ShiLab-Bioinformatics/GeneAnnotation#1]
Hello,

I would like to use the data you used in your experiments, but when I want to download the data I always get corrupted zip-files. I think it is because sharepoint has a limit for downloading data and the data is too big to be downloaded through it. I can only download the files one by one, which is rather tiresome. Do you think, you can fix this issue? 
A way to download it with wget would be really helpful.

Thanks,
Mitra

**Comment by chisangad** [comment]
Hello @MitraDarja ,
Thanks for your comments. Do you mind trying out this link and let me know if that works? 
https://cloudstor.aarnet.edu.au/plus/s/nCXBOgN2KHOZO4Q 

This has the capability to download using wget

**Comment by MitraDarja** [comment]
That worked!
Thanks a lot for the quick help!
